export const buildingData = [
    {
        ID: 1,
        NAME: 'Pintu Masuk Fakultas Teknik',
        LOCATION: [-7.766354705012508, 110.3742549061042],
        DESCRIPTION:
            'Pintu masuk menuju Fakultas Teknik dibagi menjadi 2 jalur, yaitu jalur masuk dan keluar. Terdapat pos jaga di depan pintu masuk dan di sebelah selatannya terdapat embung untuk meningkatkan konservasi air serta untuk meningkatkan kualitas micro climate di lingkungan Fakultas Teknik UGM. Untuk mengakses seluruh departemen dapat melalui jalan lingkar yang menghubungkan seluruh area di lingkungan Fakultas Teknik',
        VIDEO: 'VIDEO',
        SURROUND: 'SURROUND',
        ICON: 'ICON,',
        PATH: 'pintu-masuk',
    },
    {
        ID: 2,
        NAME: 'Tugu Teknik',
        LOCATION: [-7.766094705012508, 110.3738549061042],
        DESCRIPTION:
            'Tugu Teknik berada di bagian barat pintu masuk Fakultas Teknik. Tugu Teknik dibangun dengan wujud 3 pilar yang menyangga menyangga suatu bangun ruang dengan 8 kubus yang dihubungkan oleh 12 rusuk. Pilar berjumlah 3 melambangkan klaster pengembangan teknologi, yakni manufaktur, energi, dan infrastruktur. Sedangkan, 8 kubus melambangkan 8 departemen, 12 rusuk melambangkan 12 program studi, yang ada hingga tahun 2010 di Fakultas Teknik UGM.',
        VIDEO: 'VIDEO',
        SURROUND: 'SURROUND',
        ICON: 'ICON,',
        PATH: 'tugu-teknik',
    },
    {
        ID: 3,
        NAME: 'Lapangan Satu Bumi',
        LOCATION: [-7.766772944225647, 110.37366944848777],
        DESCRIPTION:
            'Lapangan Satu Bumi atau yang lebih dikenal sebagai Satub difungsikan sebagai sarana olahraga bagi mahasiswa Fakultas Teknik. Satub dilengkapi oleh lapangan basket dan wall climbing.',
        VIDEO: 'VIDEO',
        SURROUND: 'SURROUND',
        ICON: 'ICON,',
        PATH: 'lapangan-satub',
    },
    {
        ID: 4,
        NAME: 'Perpustakaan Fakultas Teknik',
        LOCATION: [-7.766129603887459, 110.37250797190874],
        DESCRIPTION:
            'Perpustakaan Fakultas Teknik UGM berada di sebelah selatan kompleks fakultas. Fasilitas yang dimiliki Fakultas Teknik terdiri dari ruangan koleksi buku, bilik untuk belajar mandiri, ruang diskusi, musholla, dan fasilitas berupa WiFi serta stop kontak yang disediakan secara gratis.',
        VIDEO: 'VIDEO',
        SURROUND: 'SURROUND',
        ICON: 'ICON,',
        PATH: 'perpus-ft',
    },
    {
        ID: 5,
        NAME: 'KPFT',
        LOCATION: [-7.765463687837084, 110.37234352681646],
        DESCRIPTION:
            'Dulunya, KPFT difungsikan sebagai co-working space bagi civitas akademika di Fakultas Teknik. Pada tahun 2019, gedung KPFT mulai dibangun dan berubah nama menjadi gedung Smart and Green Learning Center (SGLC) dan Engineering Research and Innovation Center (ERIC). Gedung SGLC direncanakan memiliki 11 lantai dan akan difungsikan sebagai pusat pembelajaran di Lingkungan Fakultas Teknik. Sedangkan, gedung ERIC direncanakan memiliki 5 lantai dan akan difungsikan sebagai pusat riset unggulan.',
        VIDEO: 'VIDEO',
        SURROUND: 'SURROUND',
        ICON: 'ICON,',
        PATH: 'kpft',
    },
    {
        ID: 6,
        NAME: 'Stasiun Sepeda Kampus',
        LOCATION: [-7.764737605889768, 110.37251716416931],
        DESCRIPTION:
            'Stasiun Sepeda Kampus berada di sebelah timur Masjid Teknik. Fasilitas Sepeda Kampus dapat digunakan di lingkungan UGM dan dapat dipinjam maupun dikembalikan di semua Stasiun Sepeda yang ada di area kampus UGM.',
        VIDEO: 'VIDEO',
        SURROUND: 'SURROUND',
        ICON: 'ICON,',
        PATH: 'statsiun-sepeda',
    },
    {
        ID: 7,
        NAME: 'Bookland',
        LOCATION: [-7.766090044966136, 110.37224839291424],
        DESCRIPTION:
            'Bookland menyediakan berbagai kebutuhan yang dapat menunjang kegiatan akademik mahasiswa. Bookland terletak di bawah perpustakaan fakultas dan di dekat parkiran DTETI. Civitas akademika dapat memanfaatkan bookland untuk fotokopi, print, cetak buku, membeli berbagai alat tulis, dan masih banyak lagi. Bookland menyediakan layanan dengan harga yang terjangkau.',
        VIDEO: 'VIDEO',
        SURROUND: 'SURROUND',
        ICON: 'ICON,',
        PATH: 'bookland',
    },
    {
        ID: 8,
        NAME: 'Teknik Mart',
        LOCATION: [-7.7662842347742055, 110.37275591431005],
        DESCRIPTION:
            'Teknik Mart atau yang lebih dikenal dengan sebutan Tekmart merupakan minimarket yang berada di Fakultas Teknik. Tekmart menyediakan makanan (snack), minuman, dan beberapa obat ringan. Harga yang ditawarkan cukup terjangkau dan dapat meminta nota pembayaran.',
        VIDEO: 'VIDEO',
        SURROUND: 'SURROUND',
        ICON: 'ICON,',
        PATH: 'teknik-mart',
    },
    {
        ID: 9,
        NAME: 'Kantin Fakultas Teknik',
        LOCATION: [-7.764880725665485, 110.37238808149946],
        DESCRIPTION:
            'Kantin Teknik atau biasa disingkat dengan Kantek terletak di tengah-tengah Fakultas Teknik. Terdapat kios-kios yang menjajakan makanan serta disediakan banyak meja dan kursi untuk menikmati makanan.',
        VIDEO: 'VIDEO',
        SURROUND: 'SURROUND',
        ICON: 'ICON,',
        PATH: 'kantin-ft',
    },
    {
        ID: 10,
        NAME: 'Masjid Fakultas Teknik',
        LOCATION: [-7.764657409338816, 110.37217308108933],
        DESCRIPTION:
            'Masjid Teknik merupakan tempat yang biasa digunakan oleh civitas akademika di Fakultas Teknik untuk beribadah. Masjid Teknik sudah berdiri sejak tahun 1997. Dikarenakan kurangnya daya tampung masjid saat dilakukan ibadah, terutama pada waktu sholat Jum’at, maka pada tahun 2018 dilakukan renovasi perluasan yang masih dilakukan sampai sekarang.',
        VIDEO: 'VIDEO',
        SURROUND: 'SURROUND',
        ICON: 'ICON,',
        PATH: 'masjid-ft',
    },
    {
        ID: 11,
        NAME: 'Taman AGS',
        LOCATION: [-7.764381453504416, 110.37259275415477],
        DESCRIPTION:
            'Taman AGS merupakan kependekan dari Taman Arsitektur, Geodesi, dan Sipil. Karena letaknya berada diantara DTAP, DTGD, dan DTSL membuat Taman AGS sering dikunjungi oleh civitas akademika dari ketiga departemen untuk beristirahat maupun berdiskusi di bawah pepohonan yang rindang. Taman AGS didesain dengan menerapkan konsep rain garden sebagai bagian dari infrastruktur hijau yang terbukti efektif dalam mengelola limpasan air hujan.',
        VIDEO: 'VIDEO',
        SURROUND: 'SURROUND',
        ICON: 'ICON,',
        PATH: 'taman-ags',
    },
    {
        ID: 12,
        NAME: 'Taman Segi Delapan',
        LOCATION: [-7.76574494710801, 110.37156375052805],
        DESCRIPTION:
            'Taman Segi Delapan berada di tengah kluster manufaktur, yaitu Departemen Teknik Mesin dan Industri (DTMI) serta Departemen Teknik Elektro dan Teknologi Informasi (DTETI). Tiap harinya, Taman Segi Delapan dikelilingi oleh mobil-mobil yang sedang parkir. Di pojok-pojok taman juga terdapat tempat istirahat berupa tempat duduk dibawah pohon yang digunakan untuk beristirahat sejenak.',
        VIDEO: 'VIDEO',
        SURROUND: 'SURROUND',
        ICON: 'ICON,',
        PATH: 'taman-segi-delapan',
    },
    {
        ID: 13,
        NAME: 'Departemen Teknik Arsitektur dan Perencanaan (DTAP)',
        LOCATION: [-7.764099635491441, 110.37218010478873],
        DESCRIPTION:
            'Departemen Teknik Arsitektur dan Perencanaan memiliki 2 program studi, yaitu Arsitektur dan Perencanaan Wilayah Kota (PWK). Di tengah departemen ini terdapat taman asri yang ditengahnya terdapat innercourt dan terdapat 3 buah gazebo bernama Tedjo yang biasa digunakan mahasiswa untuk bercengkrama ataupun mengerjakan tugas. Selain itu, juga terdapat fasilitas berupa ruangan studio untuk kedua program studi. Uniknya, laboratorium di DTAP disebut dengan studio dan kesekretariatan KM/HM berupa rumah pohon.',
        VIDEO: 'VIDEO',
        SURROUND: 'SURROUND',
        ICON: 'ICON,',
        PATH: 'dtap',
    },
    {
        ID: 14,
        NAME: 'Departemen Teknik Elektro dan Teknologi Informasi (DTETI)',
        LOCATION: [-7.766190415174353, 110.37179216569974],
        DESCRIPTION:
            'Departemen Teknik Elektro dan Teknologi Informasi terdiri dari 2 program studi, yaitu Teknik Elektro dan Teknologi Informasi. Pada tahun 2019, dibuka program studi baru di DTETI, yaitu Teknik Biomedis. Fasilitas yang terdapat di departemen ini diantaranya adalah co-working space dan musholla. Civitas akademika di departemen ini biasa memarkirkan kendaraan roda 2 di sebelah selatan dan timur gedung.',
        VIDEO: 'VIDEO',
        SURROUND: 'SURROUND',
        ICON: 'ICON,',
        PATH: 'dteti',
    },
    {
        ID: 15,
        NAME: 'Departemen Teknik Nuklir dan Teknik Fisika (DTNTF)',
        LOCATION: [-7.766499143887828, 110.37293869905603],
        DESCRIPTION:
            'Departemen Teknik Nuklir dan Teknik Fisika memiliki 2 program studi, yaitu Teknik Nuklir dan Teknik Fisika. Prodi Teknik Nuklir merupakan program studi satu-satunya yang ada di Indonesia dan pionir prodi Sarjana S1 Teknik Nuklir se-Asia Tenggara. Sementara itu, prodi Teknik Fisika hanya terdapat pada 6 universitas di Indonesia, termasuk UGM. Departemen ini memiliki 5 laboratorium, diantaranya adalah laboratorium energi terbarukan, laboratorium teknologi energi nuklir, laboratorium teknologi proses dan kimia nuklir, laboratorium sensor dan sistem telekontrol, dan laboratorium komputasi.',
        VIDEO: 'VIDEO',
        SURROUND: 'SURROUND',
        ICON: 'ICON,',
        PATH: 'dtntf',
    },
    {
        ID: 16,
        NAME: 'Departemen Teknik Geodesi (DTGD)',
        LOCATION: [-7.764094713714226, 110.37274848066325],
        DESCRIPTION:
            'Departemen Teknik Geodesi terdiri dari program studi Teknik Geodesi. Departemen ini memiliki fasilitas penunjang berupa lapangan voli dan musholla.  Departemen Teknik Geodesi memiliki 6 laboratorium, yaitu Laboratorium Survey dan Pemetaan, Laboratorium Hidrografi, Laboratorium Geoinformatika dan GIIG, Laboratorium Geodesi Geometrid dan Geodesi Fisis, Laboratorium Fotogrametri dan Penginderaan Jauh, Laboratorium Survei dan Pemetaan, dan Laboratorium Geokomputasi.',
        VIDEO: 'VIDEO',
        SURROUND: 'SURROUND',
        ICON: 'ICON,',
        PATH: 'dtgd',
    },
    {
        ID: 17,
        NAME: 'Departemen Teknik Geologi (DTGL)',
        LOCATION: [-7.766191092965584, 110.37319582147546],
        DESCRIPTION:
            'Departemen Teknik Geologi terdiri dari program studi Teknik Geologi. Ciri khas dari Departemen Teknik Geologi yaitu terdapat taman batu yang letaknya di beranda depan departemen ini. Departemen Teknik Geologi memiliki 9 laboratorium, yaitu Laboratorium Geologi Tata Lingkungan, Laboratorium Sedimentologi, Laboratorium Geologi Pusat, Laboratorium Geofisika, Laboratorium Bahan Galian, Laboratorium Paleontologi, Laboratorium Geologi Dinamik, Laboratorium Geologi Optik, dan Laboratorium Geokimia.',
        VIDEO: 'VIDEO',
        SURROUND: 'SURROUND',
        ICON: 'ICON,',
        PATH: 'dtgl',
    },
    {
        ID: 18,
        NAME: 'Departemen Teknik Kimia (DTK)',
        LOCATION: [-7.765421444619889, 110.37138029891758],
        DESCRIPTION:
            'Departemen Teknik Kimia terdiri dari program studi Teknik Kimia. Terdapat fasilitas berupa koridor bernama Taman Code 91 yang biasa digunakan mahasiswa untuk bercengkrama ataupun mengerjakan tugas. Departemen Teknik Kimia memiliki 12 laboratorium dan terdapat warung makan terkenal yang membuka cabang di kantin yang ada di departemen ini.',
        VIDEO: 'VIDEO',
        SURROUND: 'SURROUND',
        ICON: 'ICON,',
        PATH: 'dtk',
    },
    {
        ID: 19,
        NAME: 'Departemen Teknik Mesin dan Industri (DTMI)',
        LOCATION: [-7.76586565083204, 110.37111927885379],
        DESCRIPTION:
            'Departemen Teknik Mesin dan Industri memiliki 2 program studi, yaitu Teknik Mesin dan Teknik Industri. Departemen ini memiliki 14 laboratorium yang bertujuan untuk mendukung pencapaian hasil siswa melalui karya laboratorium yang terkait dengan kursus. Serta, terdapat 2 kesekretariatan KMHM yang bersebelahan. DTMI memiliki lapangan basket dan lapangan voli yang terletak di sebelah utara departemen ini.',
        VIDEO: 'VIDEO',
        SURROUND: 'SURROUND',
        ICON: 'ICON,',
        PATH: 'dtmi',
    },
    {
        ID: 20,
        NAME: 'Departemen Teknik Sipil dan Lingkungan (DTSL)',
        LOCATION: [-7.764561713491472, 110.373055],
        DESCRIPTION:
            'Departemen Teknik Sipil dan Lingkungan terdiri dari program studi Teknik Sipil. Pada tahun 2021, dibuka program studi baru di DTSL, yaitu Teknik Infrastruktur Lingkungan. Terdapat 7 laboratorium di departemen ini, yaitu Laboratorium Komputasi, Laboratorium Hidraulika, Laboratorium Transportasi, Laboratorium Mekanika Tanah, Laboratorium Teknik Penyehatan, Laboratorium Bahan Bangunan, dan Laboratorium Struktur.',
        VIDEO: 'VIDEO',
        SURROUND: 'SURROUND',
        ICON: 'ICON,',
        PATH: 'dtsl',
    },
];
