# Deploy assets to Netlify and transplant components to the WordPress custom code field

name: Deployment

on:
  push:
  pull_request:
    branches: [dev, prod]

jobs:
  main-job:
    runs-on: ubuntu-latest

    steps:
    - name: Prepare source files from the repo
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: npm

    - name: Prepare dependencies
      run: npm ci

    - id: prod-deploy
      name: Build and deploy for production
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/prod' }}
      run: npm run build && npm run deploy:wp
      env:
        INLINE_RUNTIME_CHUNK: 'false' # Disable inlined scripts on resulting build
        PUBLIC_URL: //kesatria-2021-resources.netlify.app
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        WP_USERNAME: ${{ secrets.WP_DEPLOY_USERNAME }}
        WP_PASSWORD: ${{ secrets.WP_DEPLOY_PASSWORD }}

    - name: Build and deploy draft/preview [Click to see deploy URL]
      if: ${{ steps.prod-deploy.outcome == 'skipped' }}
      run: npm run build && npm run deploy:draft
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
