# Deploy assets to Netlify and transplant components to the WordPress custom code field

name: Deploy and Transplant

on:
  push:
    branches: [dev, prod]
  pull_request:
    branches: [dev, prod]

jobs:
  main-job:
    runs-on: ubuntu-latest

    steps:
    - name: Prepare source files from the repo
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: npm

    - name: Prepare dependencies
      run: npm ci

    - name: Build files from source
      run: npm run build

    - id: prod-deploy
      name: Production deploy & Transplant necessary parts to WP
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/prod' }}
      run: npm run deploy:prod && npm run transplant
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        WP_USERNAME: ${{ secrets.WP_DEPLOY_USERNAME }}
        WP_PASSWORD: ${{ secrets.WP_DEPLOY_PASSWORD }}

    - name: Preview/draft deploy [Click to see deploy URL]
      if: ${{ steps.prod-deploy.outcome == 'skipped' }}
      run: npm run deploy:draft
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
